### ISSUE TITLE
test.aria.widgets.form.numberfield.inputPattern.InputPattern fails in IE11

### ISSUE THREAD

**Issue by olaf-k** [ariatemplates/ariatemplates#1265]
Failure #1: Assert #2 failed : w/o pattern is not correct, got 1000 in testAsyncStartTemplateTest()
Failure #2: Assert #3 failed : w/ pattern is not correct, got 1000 in testAsyncStartTemplateTest()

**Comment by fbasso** [comment]
This test no longer fails
