### ISSUE TITLE
test.aria.widgets.form.multiselect.downArrowKey.MultiSelect fails in IE11

### ISSUE THREAD

**Issue by olaf-k** [ariatemplates/ariatemplates#1266]
Failure #1: Uncaught error detected: [test.aria.widgets.form.multiselect.downArrowKey.MultiSelect] Exception raised while calling 'finishTest' in an asynchronous test TypeError: Unable to get property '_tplWidget' of undefined or null reference in testAsyncStartTemplateTest()

**Comment by fbasso** [comment]
This test no longer fails
