### ISSUE TITLE
Print objects with aria.core.Log

### ISSUE THREAD

**Issue by egenerat** [ariatemplates/ariatemplates#1798]
Hi,

We would like to print objects using aria.core.Log.

As you can see on the screenshot
![image](https://user-images.githubusercontent.com/5384644/41035362-50918886-6984-11e8-8667-5f7782c91eb2.png)

console.log prints objects that can be browsed easily.
this.$logInfo will just print the string [object Object].

Is it possible to improve this behaviour?

Thanks,
Emile

**Comment by ymeine** [comment]
Hello,

How about using the 3rd argument, as described here in the documentation: [aria.core.JsObject - Aria Templates API Docs](http://ariatemplates.com/aria/guide/apps/apidocs/#aria.core.JsObject:$logInfo:method)?

If you want to log only an object, without any message header apart from the classpath, you can do: `this.$logInfo('', null, myObject)`.

Technically, here's what it will do in the default Log Appender (automatically added to the logger when the logging system is loaded) which outputs messages to the browser's console: 

- it will log something only if the value of the argument returns `"object"` for `typeof`
- it will use `console.dir` if available, and only that

See that for reference: [ariatemplates/DefaultAppender.js at master · ariatemplates/ariatemplates](https://github.com/ariatemplates/ariatemplates/blob/fd3b0be255ba82e9d5a0889af9c76ab39e09b0d9/src/aria/core/log/DefaultAppender.js#L44-L46).

I personally think these are unnecessary limitations, but tell us first if that would suit you.
